### ISSUE TITLE
500 error sending data to API endpoint

### ISSUE THREAD

**Issue by iteles** [FAC-GM/gm-magic#16]
As a user, I want the extension to POST the information to the API endpoint correctly so that I can then view it in my preferred format.

<hr/>

![luke-chrome-extension-version](https://cloud.githubusercontent.com/assets/4185328/11117784/99c78f24-8934-11e5-863c-483bcec5a37e.png)
![luke-chrome-extension-error](https://cloud.githubusercontent.com/assets/4185328/11117785/99c7d7cc-8934-11e5-80e0-b107829bdcbe.png)

**Time estimate**: _To be added in sprint planning_.

**Comment by iteles** [comment]
Steps taken to test if issue is replicated when **unpacked** extension is added:
1. Download entire repository from github
2. Open extension window in chrome
3. Delete previous extension
4. Install **unpacked** extension
5. Test Chrome
**Result:** Still the same error. Debugging begins.

**Comment by SimonLab** [comment]
This issue has been resolved by parsing correctly the number linked to the skill: [L54](https://github.com/FAC-GM/gm-magic/blob/e790161d89cac7f23823f4f2f4531f27a047e21f/chrome-extension/js/scrape.js#L54)
