### ISSUE TITLE
Investigating 500 error sending data to API endpoint

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/gm-magic#17]
We are working on similar specification device to the one on which error has occurred

[See Issue16](https://github.com/FAC-GM/gm-magic/issues/16)
<hr/>

**Time estimation** : 30 min

**Comment by heron2014** [comment]
This article might be worth reading http://pcsupport.about.com/od/findbyerrormessage/a/500servererror.htm

**Comment by iteles** [comment]
Details of the computer we tried to replicate the error on:   
![screen shot 2015-11-12 at 12 21 29](https://cloud.githubusercontent.com/assets/4185328/11120282/8e0f728e-8946-11e5-8471-fb3306ad22a8.png)

Data was passed to the extension correctly:
![screen shot 2015-11-12 at 12 21 15](https://cloud.githubusercontent.com/assets/4185328/11120281/8df11ea6-8946-11e5-88bf-2863e0a3684b.png)

We were **unable to replicate the error** so we're moving on to debugging on-site #18 .

![screen shot 2015-11-12 at 12 08 54](https://cloud.githubusercontent.com/assets/4185328/11120258/7bd6241e-8946-11e5-9b9c-2145955e8325.png)
![screen shot 2015-11-12 at 12 09 02](https://cloud.githubusercontent.com/assets/4185328/11120259/7be6d4bc-8946-11e5-9c77-8ecaebcb0acd.png)
![screen shot 2015-11-12 at 12 09 09](https://cloud.githubusercontent.com/assets/4185328/11120260/7beadb34-8946-11e5-8918-436518949471.png)
![screen shot 2015-11-12 at 12 09 15](https://cloud.githubusercontent.com/assets/4185328/11120261/7beb141e-8946-11e5-9513-257ede54060c.png)
![screen shot 2015-11-12 at 12 09 22](https://cloud.githubusercontent.com/assets/4185328/11120262/7bebc31e-8946-11e5-9e86-9eeab9fcd87f.png)
![screen shot 2015-11-12 at 12 09 30](https://cloud.githubusercontent.com/assets/4185328/11120263/7bef516e-8946-11e5-9e3c-b2649b2e813a.png)
![screen shot 2015-11-12 at 12 09 35](https://cloud.githubusercontent.com/assets/4185328/11120277/8ddfe76c-8946-11e5-812b-af1b72436f1f.png)
![screen shot 2015-11-12 at 12 09 49](https://cloud.githubusercontent.com/assets/4185328/11120273/8dde7d3c-8946-11e5-860c-c0f97b5d138a.png)
![screen shot 2015-11-12 at 12 09 54](https://cloud.githubusercontent.com/assets/4185328/11120274/8ddf0590-8946-11e5-97d2-b3403f4f3e2a.png)
![screen shot 2015-11-12 at 12 10 01](https://cloud.githubusercontent.com/assets/4185328/11120278/8de1bca4-8946-11e5-8313-73840cc1fb6b.png)
![screen shot 2015-11-12 at 12 10 06](https://cloud.githubusercontent.com/assets/4185328/11120275/8ddf1918-8946-11e5-8bfd-4189258fb975.png)
![screen shot 2015-11-12 at 12 10 21](https://cloud.githubusercontent.com/assets/4185328/11120276/8ddf211a-8946-11e5-964b-3da0c9ecdabd.png)
![screen shot 2015-11-12 at 12 10 25](https://cloud.githubusercontent.com/assets/4185328/11120279/8dee2da4-8946-11e5-9de9-3aca2fae522c.png)
![screen shot 2015-11-12 at 12 10 36](https://cloud.githubusercontent.com/assets/4185328/11120280/8def1d04-8946-11e5-9fb9-5c32b4afe8ad.png)

**Comment by iteles** [comment]
We were **unable to replicate the error** so we're moving on to debugging on-site #18 .
