### ISSUE TITLE
Popup Page

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/gm-magic#20]
As a user I want to be able to access a popup page  as I want to be able to generate some actions of the extension (authentication)

**Comment by heron2014** [comment]
Pop up pages are declared in manifest.json. Example below:

![manifest](https://cloud.githubusercontent.com/assets/8476884/11298381/6f66d83c-8f76-11e5-8838-cb50de59f541.png)

[Docs](https://developer.chrome.com/extensions/overview#manifest)

**Comment by heron2014** [comment]
How do we control the size of popup.html?

**Comment by SimonLab** [comment]
![gmpopup](https://cloud.githubusercontent.com/assets/6057298/11298977/c498c168-8f7a-11e5-8f9a-3a86ca8867ef.png)

**Comment by SimonLab** [comment]
Done with [this commit](https://github.com/FAC-GM/gm-magic/commit/0072c0213913d18d82dad4b817bd6e5431a031f1)

**Comment by nelsonic** [comment]
Nice. :+1:
