### ISSUE TITLE
url not defined

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/gm-magic#29]
Check if the value of the [url](https://github.com/FAC-GM/gm-magic/blob/7f9418bcec6f69b498f8770b724f9aa5198f8e30/chrome-extension/js/scrapeNotConnected.js#L41) is defined
![urlnotpublic](https://cloud.githubusercontent.com/assets/6057298/11531530/71cc0d44-98f5-11e5-92b8-b82eeeb9510f.png)

**Comment by heron2014** [comment]
We are investigating how to pass url from window.location.href into background.js in case the situation above.

Time to research: 30min

**Comment by heron2014** [comment]
```
chrome.tabs.query({'active': true, 'lastFocusedWindow': true}, function (tabs) {
    var url = tabs[0].url;
});
```

**Comment by nelsonic** [comment]
@SimonLab good thing to investigate. you will need to strip out any URL parameters before storing the record to avoid duplicates.

**Comment by SimonLab** [comment]
The url is uniqu for each user. So it is not usefull to keep the url as other users won't be able to access it. We will just define the url as "not precise"

**Comment by SimonLab** [comment]
resolved with this [PR](https://github.com/FAC-GM/gm-magic/pull/33)
