### ISSUE TITLE
Add permission

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/gm-magic#35]
Add link in the manifest to the matches property to activate the extension on more pages

**Comment by nelsonic** [comment]
@SimonLab do we even *need* a [matches pattern](https://developer.chrome.com/extensions/match_patterns) ...?
our DOM parser should look for specific class on the page that it receives and ignore any page that does not contain the element. that way the parser can chose which pages it "*understands*".

**Comment by iteles** [comment]
Needs to be tested further with all degrees of connection.

**Comment by iteles** [comment]
Tested yesterday, but still not working with LIR.

**Comment by SimonLab** [comment]
There is still a problem with LIR but it's not a permission issue anymore

**Comment by iteles** [comment]
I suggest we close this and open a new issue :+1:

**Comment by nelsonic** [comment]
New issue. :+1:

**Comment by SimonLab** [comment]
the new issue is [44](https://github.com/FAC-GM/gm-magic/issues/35)
