### ISSUE TITLE
DOM traversing issue 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/gm-magic#36]
![screen shot 2015-12-03 at 10 49 42](https://cloud.githubusercontent.com/assets/8476884/11559568/f0f06a40-99b1-11e5-8ddf-851703e91a27.png)

**Comment by nelsonic** [comment]
We need to move away from DOM parsing in the extension ... https://github.com/FAC-GM/gm-magic/issues/27 (send all DOM to server for processing) will allow us a much more test-driven approach to this.

**Comment by heron2014** [comment]
Resolved with [PR](https://github.com/FAC-GM/gm-magic/pull/39)

**Comment by iteles** [comment]
Tested on dev team machines with `Olu Niyi-Awosusi`, a 1st degree connection on standard.
This has been shown to function correctly. Must be tested further.
