### ISSUE TITLE
Update link manifest

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/gm-magic#47]
Update with new link where the extension should works.

**Comment by iteles** [comment]
To clarify: This is so that profiles opened directly from _emails received_ are also functioning in the app.

**Comment by SimonLab** [comment]
@iteles yes the link from the email was different so we need to add thie pattern of this link into our manifest to enable "email profiles" to work with the extension

**Comment by nelsonic** [comment]
Are we able to test/confirm this is working...?

**Comment by iteles** [comment]
I just tested this with a couple of emails I had in my inbox and it worked well for me :+1: :+1: 

<img width="525" alt="screen shot 2015-12-19 at 19 45 01" src="https://cloud.githubusercontent.com/assets/4185328/11914959/2ad844a6-a689-11e5-8c48-658b892a70a1.png">
