### ISSUE TITLE
The body from LIR doesn't have all DOM elements from the profile

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/gm-magic#55]
#### update for this issue: on content-script : our else statement [L55](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/content-script.js#L55) send the body to background - how can we send body with more information (all DOM elements from LIR so we can target them)? 

These are two files (body) that we populate and send to background to be able to target elements  [LI body](https://github.com/FAC-GM/gm-magic/blob/diff-solut-lir/chrome-extension/js/draftLI.html)
and this is the body from [LIR](https://github.com/FAC-GM/gm-magic/blob/diff-solut-lir/chrome-extension/js/draft.html)
<hr />

One of the solution to populate data from LIR is : 
* [x] distinguish url from the tab: if url has 'recruiter' it means we can start populating data from LIR: 

- get url see [L7](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/background.js#L7)

- check if 'recruiter' exist and call relevant function see [L15](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/background.js#L15)

- if doesn't we do our usual see [L18](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/background.js#L18)

Issue: 

The value for degreeValue comes from [L3-L6](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/content-script.js#L3-L6)

I have checked that this value exist on LIR by inspecting document: (I am logged in as a client from our google drive information)

![degree-value](https://cloud.githubusercontent.com/assets/8476884/14282064/872a505a-fb34-11e5-8003-8e9d0cd401d6.png)

I can access the value for userName [L19](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/scrapeRecruiter.js#L19) because it exist on rendered body [L97](https://github.com/FAC-GM/gm-magic/blob/diff-solut-lir/chrome-extension/js/draft.html#L97)

If we compare two rendered body from LI and LIR we can see that they are completely different, LI one rendered all DOM elements, which makes it easy to target relevant element from the profile, LIR body only seems to rendered header and footer which I can easily target using DOM elements. 
This difference might be related to dynamically created DOM elements by LIR as opposed to LI. (These are my first thoughts). 

@nelsonic if you have a moment, could you please see if I am missing something. Thank you

To test it , we just need to manually upload chrome-extension from this branch, there is no need to zip it.

**Comment by heron2014** [comment]
Another solution would be to not distinguish between urls , but just add to relevant files new classes for properties from LIR.

**Comment by heron2014** [comment]
After my further investigation,  logging 'doc' [L12](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/background.js#L12) , are rendered differently in regular LI and LIR. I can populated data like footer information and header.. but atm I can't populate anything else on LIR. 

Difference between LI and LIR:

LIR:

![doc-lir-first-body](https://cloud.githubusercontent.com/assets/8476884/14287668/7e65ea9e-fb4b-11e5-86f5-42d2b18f5d01.png)


LI

![doc-regular-li](https://cloud.githubusercontent.com/assets/8476884/14287675/87d2a4e6-fb4b-11e5-8d9d-88dba2a14605.png)

**Comment by heron2014** [comment]
I think I have a break news -  I got value who is the LIR user.

**Comment by heron2014** [comment]
I have downloaded request.body [L7](https://github.com/FAC-GM/gm-magic/blob/test/chrome-extension/js/background.js#L7) from LI and LIR. The way we could populate other data from the profiles in Li was because we all got these information in request.body. On LIR request.body doesnt give us more information than header - footer. I can populate who is the user connected to LIR. ATM other values from the profiles are undefined in LIR.

Issue remain.

**Comment by heron2014** [comment]
I am investigating MutationObserver to detect DOM Node insertion with Javascript.

**Comment by heron2014** [comment]
In the branch diff-solut-lir - I only populate userName [L15](https://github.com/FAC-GM/gm-magic/blob/diff-solut-lir/chrome-extension/js/scrapeNotConnected.js#L15) from LIR, which also you can trigger from body [L97](https://github.com/FAC-GM/gm-magic/blob/diff-solut-lir/chrome-extension/js/draft.html#L97) (which temporarily I saved to compare ; draft - is LIR, draftLI - regular LI ). 

In this branch I am only trying to console.log data without the passing chrome.tabs .query api. 

The question is : How to get the body with all information (just like in regular LI).

**Comment by heron2014** [comment]
To resolve this issue is to wait at least 3 seconds to let JavaScript load all the DOM elements. 

We have used setTimeout function for it.

**Comment by nelsonic** [comment]
@heron2014 that will work *most* of the time, but if a consultant only views the page for 2 sec the info will not be captured...
```js
function check_available () {
  var interval = setInterval(function() {
    if(document.querySelector('.contact-info button')) {
      clearInterval(interval);
      // perform the parsing
    }
  }, 500); // check for the button every 500ms until its available
}
window.onload = check_available;
```

**Comment by SimonLab** [comment]
We should indeed use setInterval and target a specific element on the dom to be sure when the page has finished to load. However if a consultant only spend 2s on a page the page itself doesn't have the time to load all the information so we can't get the data. So can we consider that if the DOM doesn't have the time to load properly because the page is closed then we don't, we don't deal with the data?

**Comment by heron2014** [comment]
@nelsonic @iteles We have managed to populate data from LIR. Currently we are using setTimeout (3 seconds delay). We are getting personal info by listening to the click event, and after we are sending body to the background page where we can trigger DOM elements [L72-L84](https://github.com/FAC-GM/gm-magic/blob/linked-recruiter/chrome-extension/js/content-script.js#L72-L84)

**Comment by nelsonic** [comment]
@SimonLab `setTimeout` assumes that the internet speed is consistent. we *know* it isn't.

**Comment by SimonLab** [comment]
@nelsonic I'm going to use setInterval and target an element to check if it exists or not, it will be neater!
