### ISSUE TITLE
LIR user name is located in different DOM elements

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/gm-magic#58]
There are two different type of LIR accounts. On basic one - the user name is located in :
```
document.querySelector('#nav-tools-user span').textContent;
``` 
but on more professional LIR account, the user name is located in a different element (image tag)

**Comment by iteles** [comment]
Closed?

**Comment by heron2014** [comment]
Resolved by this [PR](https://github.com/FAC-GM/gm-magic/pull/59)
